### ISSUE TITLE
New SemVer Release?

### ISSUE THREAD

**Issue by trfore** [robertdebock/pre-commit#8]
First thanks for creating these pre-commit hooks! 

I was wonder if you would consider tagging and releasing the changes since `v1.5.2`? 

Also it would help if the README code examples matched the new version, as the parameter flags only work on the current `master` branch. It looks like PR #5 covers part of this change and I'll add PR #7.

Again, great work.

**Comment by robertdebock** [comment]
Just released 1.5.3, thanks!
